### DISCUSSION TITLE
id.autoIncrement equal to int.MIN, causing index error?

### DISCUSSION THREAD

**Discussion by xanmankey** [isar/isar#1042] [Help] [answered]
Hi, 

I'm using Isar on Windows to build a Flutter application, but when I try to write an instance to the database I always get the index error: `Unhandled Exception: IsarError: Unique index violated`. When the error message calls, the id of my object (and all my objects actually; I'm writing them to the database in a for loop inside the transaction) is *-9223372036854775808*, which just so happens to be the value of int.MIN. I just found the database and it looks really cool, but before I transition to manually setting ids I figured I'd ask and post my code and environment here (it's likely I'm either creating my collections wrong, instantiating instances of them wrong, or writing wrong; or perhaps a bit of all 3). 

My collection class
```dart

import 'package:adifferentwaytoplay/domain/entities/player.dart';
import 'package:isar/isar.dart';

part 'character.g.dart';

@collection
class Character {
  Id id = Isar.autoIncrement;

  // Sort Characters by names alphabetically
  @Index(unique: true, caseSensitive: false)
  late String name;

  late String image;

  @Index()
  int? age;

  String? hit;

  String? miss;

  String? description;

  // Note that the color property is a hex value
  @Index()
  int? color;

  @Index()
  int matchesPlayed = 0;

  @Index()
  int matchesWon = 0;

  @Backlink(to: 'character')
  final player = IsarLink<Player>();

  @override
  String toString() {
    return '''$id: {name: $name, image: $image, age: $age, hit: $hit, 
    miss: $miss, description: $description, color: $color, 
    matchesPlayed: $matchesPlayed, matchesWon: $matchesWon}''';
  }
}
```

My character instantiations
```dart
class CharacterData {
  static Character appleKid = Character()
    ..image = 'assets/images/appleKid.png'
    ..name = 'appleKid'
    ..hit = 'Apple inc.'
    ..miss = 'Instruction manuals'
    ..description = """appleKid is an avid apple-enthusiast, 
          touting his inventiveness and ingenuity as a result of sustained apple consumption"""
    ..color = ColorVars.red;

  static Character bananaKid = Character()
    ..image = 'assets/images/bananaKid.jpg'
    ..name = 'bananaKid'
    ..hit = 'Banana laffy taffy'
    ..miss = 'Politics'
    ..description =
        """bananaKid is an outgoing banana-believer who never misses the 
    opportunity to make a joke"""
    ..color = ColorVars.yellow;

  static Character gunlessGuy = Character()
    ..image = 'assets/images/gunlessGuy.png'
    ..name = 'gunlessGuy'
    ..hit = 'Peace'
    ..miss = 'Violence'
    ..description =
        """gunlessGuy is a zealous supporter of disarmament, showing 
    his support by carrying his Gun Deleter™ gun."""
    ..color = ColorVars.blueGrey;

  static Character dinofish = Character()
    ..image = 'assets/images/dinofish.png'
    ..name = 'dinofish'
    ..hit = 'Ressurection'
    ..miss = 'Fossils'
    ..description =
        """Also known as the coelacanth, the rare dinofish was once thought
    to be extinct and today finds enjoyment in not being so"""
    ..color = ColorVars.blueGrey;

  static Character john = Character()
    ..image = 'assets/images/hiMyNameIsJohn.jpg'
    ..name = 'John'
    ..hit = 'John'
    ..miss = 'Not john'
    ..description = """John is well-known across the world for being John"""
    ..color = ColorVars.red;

  static Character refrigeratorExhibitionGuy = Character()
    ..image = 'assets/images/refrigeratorExhibitionGuy.png'
    ..name = 'refigeratorExhibitionGuy'
    ..hit = 'Refrigerators'
    ..miss = 'Ovens'
    ..description = """If you want to buy a refrigerator, the refrigerator 
    exhibition guy is your man! A walking encyclopedia on refrigerators, he 
    knows all there is about them and effectively puts it into practice."""
    ..color = ColorVars.blue;

  static Character signPythagoreonTheorum = Character()
    ..image = 'assets/images/pythagoreanTheorumSign.png'
    ..name = 'signOfThePythagoreanTheorum'
    ..hit = 'Triangles'
    ..miss = 'Quadratics'
    ..description = """signOfThePythagoreanTheorum is great at seeing 
    multiple sides in everying situation. A very 3-dimensional character!"""
    ..color = ColorVars.brown;

  static Character signQuadraticFormula = Character()
    ..image = 'assets/images/quadraticFormulaSign.png'
    ..name = 'signOfTheQuadraticFormula'
    ..hit = 'Quadratics'
    ..miss = 'Triangles'
    ..description =
        """signOfTheQuadraticFormula likes the number 2. He's also a 
    fan of bananas (among other things) on account of their parabolic shape."""
    ..color = ColorVars.brown;

  static Character TESTCharacter = Character()
    ..image = 'assets/images/imageNoExist.png'
    ..name = 'testCharacter'
    ..hit = 'Development'
    ..miss = 'Production'
    ..description = """testCharacter is a big fan of development builds"""
    ..color = ColorVars.yellow;

  static Character TESTCharacter2 = Character()
    ..image = 'assets/images/imageNoExist.png'
    ..name = 'testCharacter2'
    ..hit = 'Development'
    ..miss = 'Production'
    ..description = """testCharacter2 likes to double check things"""
    ..color = ColorVars.yellow;
}

List<Character> characters = [
  CharacterData.appleKid,
  CharacterData.bananaKid,
  CharacterData.gunlessGuy,
  CharacterData.dinofish,
  CharacterData.john,
  CharacterData.refrigeratorExhibitionGuy,
  CharacterData.signPythagoreonTheorum,
  CharacterData.signQuadraticFormula,
];
```

Opening the database and writing the transaction
```dart
if (Isar.instanceNames.isEmpty) {
        // Create collection
        // TODO: disable inspection once app is completed
        Isar isarDB = await Isar.open(
          [
            CharacterSchema,
            GamemodeSchema,
            GamepadSchema,
            PlayerSchema,
            ProgramSchema,
            SettingSchema,
            TeamSchema,
          ],
          name: "real",
          inspector: true,
        );
        // Write initial data if the database is empty
        await isarDB.writeTxn(() async {
          /// Note that players and gamepads aren't written,
          /// because they haven't been initialized yet
          // Write Characters
          // The value of int.min just so happens to be the id of ALL my
          // characters; what significance does that have?
          // THE SIGNIFICANCE is that numerical values are used to replace
          // 'null' values in Isar, so Isar.autoIncrement = null
          print(Isar.autoIncrement);
          for (Character character in characters) {
            print(character.id);
            print(character.toString());
            await isarDB.characters.put(character);
          }
        });
        // More writes below, but I decided to only focus on writing characters for now, 
        // seeing as all my objects have the same problem
```

Pubspec.yaml
```yaml
name: adifferentwaytoplay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  window_manager: ^0.2.7
  auto_size_text: ^3.0.0
  tuple: ^2.0.1
  localstorage: ^4.0.0+1
  streaming_shared_preferences: ^2.0.0
  get_storage: ^2.0.3
  file_picker: ^5.2.2
  provider: ^6.0.4
  test: ^1.21.4
  flutter_clean_architecture: ^5.0.3
  mockito: ^5.3.2
  xinput_gamepad: ^1.2.1
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  sqflite_common_ffi: ^2.2.0+1
  go_router: ^5.2.4
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/RC.png
    - assets/images/logo.png
    - assets/images/custom_game.png
    - assets/images/FC.png
    - assets/images/TC.png
    - assets/images/tournament.png
    - assets/images/divider.png
    - assets/images/MIOP.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ComicSans
      fonts:
        - asset: assets/fonts/ComicSans/ComicSansMS3.ttf
    - family: Kaushan
      fonts:
        - asset: assets/fonts/Kaushan/KaushanScript-Regular.otf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand_Dash.otf
        # - asset: assets/fonts/Quicksand-Bold.otf
        # - asset: assets/fonts/Quicksand-Italic.otf
        # - asset: assets/fonts/Quicksand-Light.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

Flutter is version 3.3.9 and I copied version 3.0.5 of isar_windows_x64.dll to my project directory and renamed it 'isar.dll' as I had the same issue as specified here: https://github.com/isar/isar/issues/985#issue-1501354600 and that helped fix it.

Thanks again for this incredible database option!
