### DISCUSSION TITLE
[v4] how do I autoincrement my Id?

### DISCUSSION THREAD

**Discussion by SomnusVeritas** [isar/isar#1483] [Help] [answered]
Hi, in [v3] you could set Id to autoincrement by using this code:
```dart
Id id = Isar.autoIncrement;
````
In the [changelog](https://pub.dev/packages/isar/versions/4.0.0-dev.14/changelog) I read that there's a new method `collection.autoIncrement()` but **how do I use it?**

My code 
```dart
import 'package:isar/isar.dart';

@collection
class Data {
  Id id = collection.autoIncrement();
}

```
throws error
```
The method 'autoIncrement' isn't defined for the type 'Collection'.
```
pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter

  isar: ^4.0.0-dev.14

dev_dependencies:
  
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
```

**Comment by abdullah-cse** [comment]
In Pubspec.yaml,
```yaml
dependencies:
  flutter:
    sdk: flutter

  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14    //Add this line also


dev_dependencies:
  
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
```

This is your model class
```dart
import 'package:isar/isar.dart';

@collection
class Data {
   Data({
   required this.id,
   });
  //Id id = collection.autoIncrement(); //Don't use this
  final int id;  //Use this
}
```

Now where you need auto increment id, just use,
```dart
//Here your model class name is Data, so ISAR generates [datas] as your collection name
datas.autoIncrement(), //You can use this for auto increment
```
