### DISCUSSION TITLE
build_runner feat Isar

### DISCUSSION THREAD

**Discussion by guillotnico** [isar/isar#1705] [Help]
Hi,
Do you know how to manage this issue: 
```
Because build_runner >=2.4.15 depends on build_resolvers ^2.4.4 which depends on analyzer >=6.9.0 <8.0.0, build_runner >=2.4.15 requires analyzer >=6.9.0 <8.0.0.
And because isar_generator 3.1.0+1 depends on analyzer >=4.6.0 <6.0.0 and no versions of isar_generator match >3.1.0+1 <4.0.0, build_runner >=2.4.15 is incompatible with isar_generator ^3.1.0+1.
So, because meludia depends on both isar_generator ^3.1.0+1 and build_runner ^2.4.15, version solving failed.
```
pubspec.yaml: 
```
dependencies:
  flutter:
    sdk: flutter
  
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.15
```
Thanks
