### ISSUE TITLE
Missing type arguments for generic method 'addPropertyName<E>'.

### ISSUE THREAD

**Issue by ivanesi** [isar/isar#1001]
Missing type arguments for generic method 'addPropertyName<E>'.
Try adding an explicit type, or remove implicit-dynamic from your analysis options file.

### Code sample

```dart
QueryBuilder<DbAppTask, DateTime, QQueryOperations> endDateProperty() {
    return QueryBuilder.apply(this, (query) {
      return query.addPropertyName(r'endDate');
    });
  }
```

### Details
 - isar: ^3.0.5

**Comment by Jure-BB** [comment]
Workaround: add `exclude: [**.g.dart]` into `analysis_options.yaml`.

```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/**.g.dart
```
