### ISSUE TITLE
☂️ Isar v4

### ISSUE THREAD

**Issue by simc** [isar/isar#1344]
This issue will be filled with information about Isar v4. Including missing features and open issues.

**Comment by richard457** [comment]
The missing features I believe are:

- [ ]  Web

- [ ] Synchronization

**Comment by itisnajim** [comment]
I encountered :
  ```bash
  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError
```
when using the `countAsync()` method in the version `^4.0.0-dev.3`. This issue occurs in the context of the following code snippet:
```dart
Future<Map<LocalLevel?, int>> getLevelCountMap() async {
    final isar = await _database.open();

    final res = await Future.wait(
      LocalLevel.values.map((level) async {
        final count =
            await isar.localLogs.where().levelEqualTo(level).countAsync();
        return MapEntry(level, count);
      }),
    );

    final totalCount = res.map((e) => e.value).reduce((v, e) => v + e);
    return Map.fromEntries([MapEntry(null, totalCount), ...res]);
  }
  ```

pubspec.yaml:
```yaml
...
dependencies:
  flutter:
    sdk: flutter
  ...
  isar: ^4.0.0-dev.3
  isar_flutter_libs: ^4.0.0-dev.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
```

The database.open() method is called with the following configuration:
```dart
Isar.open(
  schemas: schemas,
  name: name,
  encryptionKey: encryptionKey,
  engine: IsarEngine.sqlite,
  maxSizeMiB: 512,
  // set to true to enable the inspector
  inspector: false,
  directory: directory,
)
```

am i missing something?
