### ISSUE TITLE
Error on last version v3.10.1+1: Could not initialize IsarCore library for processor architecture "android_arm"

### ISSUE THREAD

**Issue by FernandoUFS** [isar/isar#1420]
I'm receiving lots of Crashlytics reports with the following error: 
`IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found`

This is my code to initialize Isar
```dart
final dir = await getApplicationDocumentsDirectory();
isar = await Isar.open(
    [IsarSelSchema, IsarTagSchema, IsarResultSchema],
    directory: dir.path,
);
```

I've checked same issues that are closed, but the problem still persists in the last version
For this one:
#831
My minSdkVersion is already 21
```
minSdkVersion 21
targetSdkVersion 33
```

For this:
#1096
It's saying it was solved in the version 3.1.0, but it was not. People still complaining about this error there, the issue is closed without proper attention.

### pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  
  flutter_modular: ^5.0.3 # Dependency injection system and router
  path_provider: ^2.0.15 # Get path to app data folder
  intl: ^0.18.1 # Internationalization and converters
  path: ^1.8.3 # Manipulate paths
  
  # Storage
  shared_preferences: ^2.2.0 # Store user preferences
  sqflite_common_ffi: any # Used to get old database path
  sqflite: ^2.2.8+4 # Read old sqlite databases
  hive: ^2.2.3 # NoSQL database for web and mobile, used to store tickets on web
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # UI
  dotted_line: ^3.2.2    

dev_dependencies:
  flutter_test:
    sdk: flutter
  modular_test: any
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  isar_generator: ^3.1.0+1
  collection: ^1.17.1
```

### Details
 - Platform: reported on Android 5.1.1, 6.0 and 6.0.1
 - Flutter version: 3.13.0
 - Isar version: 3.1.0+1

The devices reported with this issue are:
Galaxy J1 (2016)
Galaxy Grand Prime Plus
Galaxy J1 Mini
Galaxy J7
Galaxy Grand Prime
Galaxy J3
Galaxy J2 Prime
LG K4/K7 (2017)

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by FernandoUFS** [comment]
I'm getting lots of negative reviews from people using these devices. I have no clue on how to fix it.

**Comment by marcotta** [comment]
I have started to see this problem today too and I am also using version 3.1.0+1
from pubspec.lock

```
  isar:
    dependency: transitive
    description:
      name: isar
      sha256: "99165dadb2cf2329d3140198363a7e7bff9bbd441871898a87e26914d25cf1ea"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.0+1"
  isar_flutter_libs:
    dependency: transitive
    description:
      name: isar_flutter_libs
      sha256: bc6768cc4b9c61aabff77152e7f33b4b17d2fc93134f7af1c3dd51500fe8d5e8
      url: "https://pub.dev"
    source: hosted
    version: "3.1.0+1"
```

Doctor summary 
```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.5.2 22G91 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

Device reported:
Brand: Samsung
Model: Galaxy A54 5G
Version: Android 13

Analyzing the `aab` I can see there is `libsar.so` in :
* x86_64
* arm64-v8a
* armeabi-v7a
