### ISSUE TITLE
[v4] Missing features: autoIncrement, indices, filter, links

### ISSUE THREAD

**Issue by frank06** [isar/isar#1450]
I'm porting a codebase from Isar 3 to Isar 4 (because that code is also using Hive 4, that requires Isar 4)

I noticed several missing features:
 - `Isar.autoIncrement`
 - Indices have way less features than described https://isar.dev/indexes.html , for example there is no index type to declare an `IndexType.values`, there is no `replace`, but more importantly for us:
   - composite indices do not generate the appropriate code for querying: e.g. a `type`/`id` will not generate a corresponding `typeIdEqualTo` which suggested indices are not properly leveraged?
  - It's only possible to use `where()` in queries, not sure if there's a difference now with `filter()`?
  - `@IsarLink` not available, are links gone?

**Comment by giga10** [comment]
Just passing by... 

https://pub.dev/packages/isar/versions/4.0.0-dev.14/changelog

**Comment by frank06** [comment]
Yes I missed that, thank you!

**Comment by SomnusVeritas** [comment]
Hi, I'm trying to use collection.autoIncrement(), but my compiler tells me the function doesn't exist.

![image](https://github.com/isar/isar/assets/133667014/45fb0d89-4488-4512-a2fc-6b6e61fbd053)

pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
```
