### ISSUE TITLE
Please upgrade isar_generator dependencies

### ISSUE THREAD

**Issue by arnab** [isar/isar#1468]
While using [`isar_generator`](https://pub.dev/packages/isar_generator), the latest version:  

```yaml
isar_generator: ^3.1.0+1
```

... I regularly see dependency conflict errors with other generators. e.g.: We can't use the `riverpod_lint` package while using `isar_generator`:

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.1
```

Error:

```
Because riverpod_lint >=2.2.1 depends on analyzer ^6.0.0 and isar_generator 3.1.0+1 depends on analyzer >=4.6.0 <6.0.0, riverpod_lint >=2.2.1 is incompatible with isar_generator 3.1.0+1.
And because no versions of isar_generator match >3.1.0+1 <4.0.0, riverpod_lint >=2.2.1 is incompatible with isar_generator ^3.1.0+1.
So, because orcapod_app depends on both isar_generator ^3.1.0+1 and riverpod_lint ^2.3.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on riverpod_lint: flutter pub add dev:riverpod_lint:^2.1.1
```
