### ISSUE TITLE
Pure Dart support

### ISSUE THREAD

**Issue by cachapa** [isar/isar#15]
I just played around with the current state and noticed that the generator imports Flutter packages, specifically `path_provider` and `flutter` even though my project doesn't depend on `isar_flutter`.

Is pure Dart support planned? That's one of the great things about Hive that I would like to see continued here if possible.

**Comment by leisim** [comment]
@cachapa It is possible to use Isar with Dart only. The unit tests do that for example.

The isar_flutter package contains the binaries of isar_core. But you can also provide them yourself. I'll document how to do that 👍

**Comment by cachapa** [comment]
Ok thanks. I did see the unit tests but was confused because the generator in my dart-only project generated those flutter dependencies.

**Comment by leisim** [comment]
The generator has a flutter option. Add this to your build.yaml to disable it:
```yaml
targets:
  $default:
    builders:
      isar_generator|generator:
        options:
          flutter: false
```

Example: https://github.com/isar/isar/blob/main/isar/build.yaml
