### ISSUE TITLE
[BUG] 🐛 Update `dart_style` version

### ISSUE THREAD

**Issue by moha-b** [isar/isar#1697]
### Description
Hi there,

I'm encountering a dependency conflict when trying to integrate `isar_generator 3.1.0+1` into my project. The issue arises because isar_generator depends on `dart_style ^2.2.3`, but my project (or another dependency, such as flutter_gen) requires `dart_style ^3.0.0`. This results in a version-solving failure, as shown by the following error:
```shell
Resolving dependencies...
Because isar_generator 3.1.0+1 depends on dart_style ^2.2.3 and no versions of isar_generator match >3.1.0+1 <4.0.0, isar_generator ^3.1.0+1 requires dart_style ^2.2.3.
So, because sanad depends on both dart_style ^3.0.0 and isar_generator ^3.1.0+1, version solving failed.
```
it's similar to #1468 

### Steps to Reproduce
1. add isar to your project
2. in my case add `flutter_gen`
3. force `dart_style` to its last version
4. add also `build_runner` 
5. dependency overrides `analyzer: ^7.3.0`
6. pub get

### Code sample

```yaml
dependencies:
  flutter_gen: ^5.9.0
  dart_style: ^3.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  isar_generator: ^3.1.0+1
  flutter_gen_runner:
  build_runner: ^2.4.15

dependency_overrides:
  analyzer: ^7.3.0
```

### Details
 - Flutter version: [3.29.0]
 - Isar version: [latest version]
```shell
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale en-US)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.5)
[√] Android Studio (version 2024.2)
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
[√] Connected device (4 available)
[√] Network resources
```
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example
