### ISSUE TITLE
Example has crashed at start

### ISSUE THREAD

**Issue by ValeriusGC** [isar/isar#291]
As mentioned in documentation an example [is here](https://github.com/isar/samples/tree/main/quotes)
But it crashes at start on emulator and android device with exception:
```
Observatory server failed to start after 10 tries
I/flutter (16645): Observatory server failed to start after 11 tries
I/flutter (16645): Could not start Observatory HTTP server:
I/flutter (16645): SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 0
I/flutter (16645): #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:996:7)
I/flutter (16645): <asynchronous suspension>
I/flutter (16645): #1      Server.startup.poll (dart:vmservice_io/vmservice_server.dart:425:19)
I/flutter (16645): <asynchronous suspension>
I/flutter (16645): #2      Server.startup (dart:vmservice_io/vmservice_server.dart:437:13)
I/flutter (16645): <asynchronous suspension>
```
**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on Ubuntu 20.04.4 LTS 5.13.0-35-generic, locale en_US.UTF-8)                                                                                   [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by richard457** [comment]
@ValeriusGC which platform are you running the sample on?

**Comment by richard457** [comment]
is it 64 bit? because 32 bit is not supported there is a bug that needs to be fixed. https://github.com/isar/isar/issues/187

**Comment by zexross** [comment]
@ValeriusGC Please add the tag for granting access to internet usage in the **AndroidManifext.xml** file:
```
<uses-permission android:name="android.permission.INTERNET"/>
```

After adding this and running the example app again. Things should work fine hopefully!

**Comment by ValeriusGC** [comment]
> @ValeriusGC Please add the tag for granting access to internet usage in the **AndroidManifext.xml** file:
> <uses-permission android:name="android.permission.INTERNET"/>

Now i stuck with next error: `Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found`
```
I/flutter ( 2922): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
E/flutter ( 2922): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
E/flutter ( 2922): #0      initializeIsarCore (package:isar/src/native/isar_core.dart:68:5)
E/flutter ( 2922): #1      openIsarNative (package:isar/src/native/open.dart:27:3)
E/flutter ( 2922): <asynchronous suspension>
E/flutter ( 2922): #2      main (package:quotes/main.dart:12:16)
E/flutter ( 2922): <asynchronous suspension>
```

**Here is my YAML**
```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^1.0.0
  isar_flutter_libs: ^1.0.0
  isar_connect: ^1.0.0
  lazy_load_scrollview: 1.3.0
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: 0.4.0-nullsafety.3
  path_provider: ^2.0.8 

dev_dependencies:
  isar_generator: ^1.0.0
  build_runner: any
```
**I tried update to last ones ...**
```
dependencies:
  flutter:
    sdk: flutter
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  isar_connect: 2.0.0
  lazy_load_scrollview: 1.3.0
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.6.1
  path_provider: ^2.0.9

dev_dependencies:
  isar_generator: ^2.2.1
  build_runner: any
```
**... but faced with conflicts:**
```
Because isar_connect 2.0.0 depends on isar 2.0.0 and quotes depends on isar ^2.2.1, isar_connect 2.0.0 is forbidden.
So, because quotes depends on isar_connect 2.0.0, version solving failed.

```
