### ISSUE TITLE
Getting Error : 'The plugin `isar_flutter_libs` doesn't have a main class'

### ISSUE THREAD

**Issue by hosseinhadi** [isar/isar#34]
**Steps to Reproduce**

When I try to `pub get` , I get this error :
```

The plugin `isar_flutter_libs` doesn't have a main class defined in C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\isar_flutter_libs-0.1.0\android\src\main\java\dev\isar\isar_flutter_libs\IsarFlutterPlugin.java or C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\isar_flutter_libs-0.1.0\android\src\main\kotlin\dev\isar\isar_flutter_libs\IsarFlutterPlugin.kt. This is likely to due to an incorrect `androidPackage: dev.isar.isar_flutter_libs` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.
```
And the process of getting package terminates.

**Code sample**
My `pubspec.yaml`
```
name: app_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  isar: 0.1.0
  isar_flutter_libs: 0.1.0
  koukicons: 2.0.3
  reorderables: 0.3.2
  lorem_cutesum: 1.0.0
  align_positioned: 2.0.0
  simple_animations: 3.0.1
  supercharged: 2.0.0
  animate_do: 2.0.0
  google_fonts: ^1.1.2
  get: ^3.26.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 0.1.0
  build_runnder: 0.1.0

flutter:

  uses-material-design: true
```

**Version**
My `flutter doctor`:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)
