### ISSUE TITLE
Severe isar_generator could not resolve annotaion for int? id

### ISSUE THREAD

**Issue by EE1234EE** [isar/isar#499]
**Steps to Reproduce**
Hello first of all thank you very much for that great db! 
If I run flutter pub run build_runner build I get following error:

**RangeError: Index: 0, Size: 0**
**[SEVERE] isar_generator:isar_generator on lib/collections/category.dart:**

**Could not resolve annotation for `int? id`.**
**[WARNING] isar_generator:isar_generator on lib/collections/routine.dart:**
**An unexpected error was thrown trying to get location information on `int? id` (FieldElementImpl).**

My pubspec.yaml
```
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar: ^3.0.0-dev.8
  isar_generator: ^3.0.0-dev.8
  build_runner: ^2.2.0
  path_provider: ^2.0.11
  isar_flutter_libs: ^3.0.0-dev.8

dev_dependencies:
  flutter_test:
    sdk: flutter`
```

Category class:
```

import 'package:isar/isar.dart';
part 'category.g.dart';

@Collection()
class Category {

    @Id()
    int? id; // = Isar.autoIncrement;

    @Index(unique: true)
    late String name;

    // String get name => _name;
    //
    // set name(String value) {
    //   _name = value;
    // }
}
```

and the routine class
```
import 'package:isar/isar.dart';
import 'package:isar_database_tutorial/collections/Category.dart';
part 'routine.g.dart';

@Collection()
class Routine {

  @Id()
  int? id; // = Isar.autoIncrement;

  @Index(composite: [CompositeIndex('title')])
  final category = IsarLink<Category>();

  late String title;

  @Index()
  late DateTime startTime;

  @Index(caseSensitive: false)
  late String day;

  // String get title => _title;
  //
  // set title(String value) {
  //   _title = value;
  // }
  //
  // DateTime get  startTime => _startTime;
  //
  // set startTime(DateTime value) {
  //   _startTime = value;
  // }
  //
  // String get day => _day;
  //
  // set day(String value) {
  //   _day = value;
  // }
}
```
I'm just coding along the youtube tutorial, any idea to resolve the error?
flutter clear --> flutter pub get run multiple times with always some other code (id annotation and id initialization) still same error.
