### ISSUE TITLE
isar_flutter_libs_plugin.dll is flagged as infected

### ISSUE THREAD

**Issue by Mangiang** [isar/isar#582]
**Steps to Reproduce**
1. Create a new Flutter project
2. Install `isar`, `isar_flutter_libs` and `isar_generator` (no need to even import in dart files)
3. Build and run the application either in Release or Debug mode
4. Notice Bitdefender flagging `isar_flutter_libs_plugin.dll` as infected with `Gen:Variant.Tedy.191473`
![image](https://user-images.githubusercontent.com/9913715/186334897-ff5e7531-8605-4125-b0a1-83a7f81d1eb7.png)

**Code sample**
```yml
name: my_app
description: An example app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  xml: ^5.3.1
  file_picker: ^4.6.1
  path_provider: ^2.0.11
  yaml: ^3.1.1
  crypto: ^3.0.2
  yaml_writer: ^1.0.2
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0

dev_dependencies:
  isar_generator: ^2.5.0
  build_runner: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

**Version**
 - Platform: Windows
 - Flutter version: 3.0.5
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0
 - [VirusTotal analysis](https://www.virustotal.com/gui/file/d060fdfb6081ddd3b5d58910d32bbe01befb43a30a641b4b23e7e4b7e6685f0a?nocache=1)
