### ISSUE TITLE
mismatch version isar connect and isar

### ISSUE THREAD

**Issue by dgandhi17** [isar/isar#65]
Because every version of isar_connect depends on isar 0.2.0 and map_app depends on isar ^0.4.0, isar_connect is forbidden.
So, because map_app depends on isar_connect any, version solving failed.
pub get failed (1; So, because map_app depends on isar_connect any, version solving failed.)

**Comment by barbalex** [comment]
I am getting similar error: 

```
Running "flutter pub get" in record_data...                     
Because every version of isar_connect depends on isar 0.2.0 and record_data depends on isar ^0.4.0, isar_connect is forbidden.

So, because record_data depends on isar_connect ^0.2.0, version solving failed.
pub get failed (1; So, because record_data depends on isar_connect ^0.2.0, version solving failed.)
exit code 1
```

When using:
```
  isar: ^0.4.0
  isar_flutter_libs: ^0.4.0 # contains the binaries
  isar_connect: ^0.2.0
  isar_generator: ^0.4.0
  build_runner: ^1.12.2
```

**Comment by leisim** [comment]
I didn't have time to release a new isar_connect version yet. Will do today or tomorrow

**Comment by saeed-golshan** [comment]
You are a super hero with so many good project 👍🏻. Share anything that others can help you for better and fast development.

**Comment by savy-91** [comment]
Hi! Is there any update about this?

**Comment by igoriuz** [comment]
This should work:

```
dependencies:
  isar: 0.4.0
  isar_flutter_libs: ^0.4.0 # contains the binaries
  isar_connect: # ^0.2.0 # if you want to use the Isar Inspector
    git:
      url: git@github.com:isar/isar.git
      path: packages/isar_connect

dev_dependencies:
  isar_generator: ^0.4.0
```

**Comment by monkeydaichan** [comment]
> This should work:
> 
> ```
> dependencies:
>   isar: 0.4.0
>   isar_flutter_libs: ^0.4.0 # contains the binaries
>   isar_connect: # ^0.2.0 # if you want to use the Isar Inspector
>     git:
>       url: git@github.com:isar/isar.git
>       path: packages/isar_connect
> 
> dev_dependencies:
>   isar_generator: ^0.4.0
> ```

@igoriuz 
Thank you!
It is working for me

**Comment by om-ha** [comment]
@igoriuz 

Thanks for your solution! It didn't work for me unfortunately, but it put me in the right track: I had to modify git protocol from ssh to https, like so:

```yaml
dependencies:
  # ...some other dependencies...
  # isar
  isar: 0.4.0
  isar_flutter_libs: ^0.4.0 # contains the binaries
  isar_connect: # ^0.2.0 # if you want to use the Isar Inspector
    git:
      url: https://github.com/isar/isar.git
      path: packages/isar_connect

dev_dependencies:
  # ...some other dev_dependencies...
  # isar
  isar_generator: ^0.4.0
  build_runner: any
```
