### ISSUE TITLE
3.0.0-dev.15 version solving failed

### ISSUE THREAD

**Issue by jannikrh** [isar/isar#675]
### Steps to Reproduce

Upgrade to the latest dev version 15 of Isar and associated packages.

```
Because every version of isar_flutter_libs depends on flutter from sdk which depends on meta 1.7.0, every version of isar_flutter_libs requires meta 1.7.0.
And because isar >=3.0.0-dev.15 depends on meta ^1.8.0, isar_flutter_libs is incompatible with isar >=3.0.0-dev.15.
So, because app_storage depends on both isar 3.0.0-dev.15 and isar_flutter_libs 3.0.0-dev.15, version solving failed.
```

### Code sample

Sample of `pubspec.yaml`
```yaml
name: app_storage
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  isar: 3.0.0-dev.15
  isar_flutter_libs: 3.0.0-dev.15

dev_dependencies:
  build_runner: ^2.2.0
  isar_generator: 3.0.0-dev.15
```

### Details

 - Flutter version: 3.0.5
 - Isar version: 3.0.0-dev.15

Great work on this package. I am currently in the process of migrating from Hive to Isar and am already excited about the possibilities.
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example
