### ISSUE TITLE
The following build commands failed: .../iphoneos/isar_flutter_libs.framework/isar_flutter_libs normal arm64

### ISSUE THREAD

**Issue by Hesamedin** [isar/isar#740]
### Steps to Reproduce
I am not sure if this issue is related to Isar directly so please close if you don't think so. This is the first time I am integrating Isar db into my project. I am able to use the Isar database in my app correctly. So, I don't have any problem with the integration and build.
I am also able to export the app via XCode.
My problem is in Export IPA using the command line via Azure CLI (CI/CD stuff).

This is part of the logs I think might be related to the issue:
```
=== BUILD TARGET isar_flutter_libs OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
.
.
.

Ld /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/isar_flutter_libs.framework/isar_flutter_libs normal arm64
    cd /Users/runner/work/1/s/ios/Pods
    export PATH="/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin:/Users/runner/work/1/s/flutter/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.9.1/x64"
    /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios13.0 -dynamiclib -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -L/Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/isar_flutter_libs -L/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/isar_flutter_libs -L/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -F/Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/isar_flutter_libs -F/Users/runner/work/1/s/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64 -F/Users/runner/work/1/s/ios/Pods/../.symlinks/plugins/isar_flutter_libs/ios -filelist /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/isar_flutter_libs.build/Objects-normal/arm64/isar_flutter_libs.LinkFileList -install_name @rpath/isar_flutter_libs.framework/isar_flutter_libs -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/isar_flutter_libs.build/Objects-normal/arm64/isar_flutter_libs_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/isar_flutter_libs -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/isar_flutter_libs.build/Objects-normal/arm64/isar_flutter_libs.swiftmodule -lisar -framework Flutter -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/isar_flutter_libs.build/Objects-normal/arm64/isar_flutter_libs_dependency_info.dat -o /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/isar_flutter_libs.framework/isar_flutter_libs
ld: Invalid value (Producer: 'LLVM14.0.5-rust-1.63.0-stable' Reader: 'LLVM APPLE_1_1300.0.29.30_0') for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

and this is the end of the log:
```
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/isar_flutter_libs.framework/isar_flutter_libs normal arm64
(1 failure)
##[error]Error: The process '/usr/bin/xcodebuild' failed with exit code 65
```

### Code sample
This is my Xcode task:
```
  - task: Xcode@5
    displayName: 'Export ipa (Release)'
    inputs:
      actions: 'clean'
      scheme: 'Runner'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
      xcWorkspacePath: '$(projectDirectory)/ios/Runner.xcworkspace'
      useXcpretty: false
      teamId: '$(dev_team_id)'
      args: '-UseModernBuildSystem=NO DEVELOPMENT_TEAM=$(dev_team_id)'
      packageApp: true
      archivePath: '$(projectDirectory)/ios/output/build/archive'
      exportPath: '$(projectDirectory)/ios/output/build/export'
      exportOptions: 'auto'
      signingOption: 'manual'
      signingIdentity: $(codesign_identity)
      provisioningProfileUuid: $(APPLE_PROV_PROFILE_UUID)
```

This is the command line that is generated by the above task:
```
/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace /Users/runner/work/1/s/ios/Runner.xcworkspace -scheme Runner clean -UseModernBuildSystem=NO DEVELOPMENT_TEAM=<my-team-id> CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=<my-code-sign-identity> PROVISIONING_PROFILE=<my-provisioning-profile> PROVISIONING_PROFILE_SPECIFIER=

```

### Details

 - Platform: mobile, iphone.
 - Flutter version: 3.3.3, Stable channel, Dart: 2.18.2, Dev Tools: 2.15.0
 - Isar version: 3.0.2 (I had the issue on 3.0.1, too)

---

 - [x] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example
