### ISSUE TITLE
Problem with ISAR and "infinite_scroll_pagination"

### ISSUE THREAD

**Issue by ziobudda** [isar/isar#751]
I'm using ISAR for my project and now I want to add an infinite scroll pagination, but when I exec 

`# flutter pub add infinite_scroll_pagination`

I receive this error: 

```
ERR : Unsupported operation: Encountered an alias node along [dependencies, isar]! Alias nodes are nodes that refer to a previously serialized nodes, and are denoted by either the "*" or the "&" indicators in the original YAML. As the resulting behavior of mutations on these nodes is not well-defined, the operation will not be supported by this library.
    | 
    | line 4, column 15: The alias was first defined here.
    |   ╷
    | 4 │ isar_version: &isar_version 3.0.1
    |   │               ^^^^^^^^^^^^^^^^^^^
    |   ╵
FINE: Exception type: AliasError
ERR : package:yaml_edit/src/editor.dart 500:34  YamlEditor._assertNoChildAlias
    | package:yaml_edit/src/editor.dart 516:9   YamlEditor._assertNoChildAlias
    | package:yaml_edit/src/editor.dart 484:21  YamlEditor._traverse
    | package:yaml_edit/src/editor.dart 251:24  YamlEditor.update
    | package:pub/src/command/add.dart 413:18   AddCommand._updatePubspec
    | package:pub/src/command/add.dart 174:7    AddCommand.runProtected

```

In my pubspec.yml I have : 

```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  isar_generator: *isar_version
  path_provider: ^2.0.11
  build_runner: any
  google_fonts: ^3.0.1
  dio: ^4.0.6
  flash: ^2.0.3+3
  provider: ^6.0.3
  file_picker: ^5.2.0+1
  open_file: ^2.1.1
  carousel_slider: ^4.1.1
  hovering: ^1.0.4
```

If I substitute ***isar_version** with **^3.0.1** all works.

I have open an indentical issue in "dart language" repository.
