### ISSUE TITLE
IsarError: Could not initialize IsarCore library for processor architecture "android_arm"

### ISSUE THREAD

**Issue by asorokin** [isar/isar#831]
### Steps to Reproduce

Running my Flutter app on physical device OnePlus X Android 6.0.1 and getting this error:
`IsarError (IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.
Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found)`

I have isar_flutter_libs added in my dependencies:

```
isar_version: &isar_version 3.0.2

dependencies:
  # isar db
  isar: *isar_version
  isar_flutter_libs: *isar_version
```

Is there anything that can be done to fix it?

Your help is greatly appreciated! Thanks!
Andy

### Details

 - Platform: Android 6.0.1, OnePLus X physical device.
 - Flutter version: [Flutter 3.3.3 • channel stable]
 - Isar version: [3.0.2]
