### ISSUE TITLE
Failed to load dynamic lib on pure dart project

### ISSUE THREAD

**Issue by md-weber** [isar/isar#962]
I created a quite small project that uses FFI and wants to save some information I receive from it. I do not include the flutter_libs and run it on a pure dart project.

Current working OP: Windows 64bit system

When I execute the program, the following error appears:

```
Invalid argument(s): Failed to load dynamic library 'C:\Users\weber\dev\dart_projects\window_selector\.dart_tool\pub\bin\window_selector\isar.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _initializePath (package:isar/src/native/isar_core.dart:92:28)
#3      initializeCoreBinary (package:isar/src/native/isar_core.dart:75:9)
#4      openIsar (package:isar/src/native/open.dart:81:3)
#5      Isar.open (package:isar/src/isar.dart:107:12)
#6      ProgramRepository.initDB (package:window_selector/repository/isar/program_repo.dart:11:45)
===== HINT:    Future<Isar> initDB() async => await Isar.open([ProgramSchema]); ==== 
#7      new ProgramRepository (package:window_selector/repository/isar/program_repo.dart:8:12)
#8      main (file:///C:/Users/weber/dev/dart_projects/window_selector/bin/window_selector.dart:7:22)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

pubspec.yaml

```
name: window_selector
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  isar: ^3.0.5
  win32: ^3.1.2
dev_dependencies:
  build_runner: ^2.3.2
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
```

I thought it is maybe related to https://github.com/isar/isar/issues/48 but it seems to be resolved and after reading into it did not solve the issue for me.
